# ECS datasource from environment variables (Task Definition)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ECS JPA: don't destroy schema
spring.jpa.hibernate.ddl-auto=validate

# ECS Flyway: usually ON in real deployments (you can keep false for now)
spring.flyway.enabled=false

# Bucket per env (set from task env if you want)
aws.s3.bucket=${AWS_S3_BUCKET:devcool-media}
