# Local: let Spring Boot start docker compose dependencies when you run app from IntelliJ
spring.docker.compose.lifecycle-management=start_only
spring.docker.compose.file=./docker/local/compose.yaml

# Local datasource (host app -> docker db)
spring.datasource.url=jdbc:postgresql://localhost:5432/devcool
spring.datasource.username=hiengiang
spring.datasource.password=123456789

# Local JPA
spring.jpa.hibernate.ddl-auto=validate

# Local Flyway
spring.flyway.enabled=false

# Local bucket
aws.s3.bucket=devcool-media-local
