services:
  postgres:
    container_name: devcool_postgres
    image: 'postgres:15'
    environment:
      POSTGRES_DB: devcool
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: hiengiang
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-hiengiang} -d ${POSTGRES_DB:-devcool}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    container_name: devcool_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - '5050:5050'
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'devcool_postgres:5432:*:hiengiang:123456789' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
volumes:
  postgres:
  pgadmin:
