package com.devcool.domain.common;

public enum ErrorCode {
  USER_NOT_FOUND("USR_404"),
  USER_DUPLICATE("USR_405"),
  EMAIL_ALREADY_USED("USR_409"),
  USERNAME_ALREADY_USED("USR_410"),
  PASSWORD_WEAK("USR_422"),
  PASSWORD_INCORRECT("USR_223"),
  PASSWORD_NOT_MATCH("USR_224"),
  REFRESH_TOKEN_INVALID("AUTH_225"),
  PASSWORD_DUPLICATE("USR_225"),
  VALIDATION_ERROR("VLD_401"),
  INTERNAL_SERVER_ERROR("SVR_500"),
  INVALID_CHANNEL_CONFIG("CHANNEL_400"),
  CHANNEL_NOT_FOUND("CHANNEL_401"),
  DUPLICATE_MEMBER("CHANNEL_402"),
  MEMBER_NOT_FOUND("MEMBER_404"),
  FORBIDDEN("SVR_403"),
  OK("SVR_200"),
  CREATED("SVR_201");

  private final String code;

  ErrorCode(String code) {
    this.code = code;
  }

  public String code() {
    return code;
  }
}
